image: docker:20.10.16
services:
  - docker:20.10.16-dind

stages:
  - build

variables:
  CONTAINER_IMAGE: dsolopenkov/k8s-with-gitlab:${CI_COMMIT_SHORT_SHA}

build:
  stage: build
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE}
    - docker tag ${CONTAINER_IMAGE} dsolopenkov/k8s-with-gitlab:latest
    - docker push ${CONTAINER_IMAGE}
